### ISSUE TITLE
码云上面的也是你传的吗，两个版本的提交记录差好多哦，国内的网下github就几kb/s

### ISSUE THREAD

**Issue by prefectover** [XINCGer/Unity3DTraining#1]

**Comment by icebincb** [comment]
我有点懵逼，我只是收藏了，这个项目啥都没动…emmmm 外加下载了一下 你是不是发错邮箱了？------------------ 原始邮件 ------------------
发件人: "LiuXiong"<notifications@github.com>
发送时间: 2019年12月17日(星期二) 中午1:28
收件人: "XINCGer/Unity3DTraining"<Unity3DTraining@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [XINCGer/Unity3DTraining] 码云上面的也是你传的吗，两个版本的提交记录差好多哦，国内的网下github就几kb/s (#1)


 
&mdash;

**Comment by XINCGer** [comment]
是我的项目，码云上面那个很久没有更新过了

**Comment by renmogouyang** [comment]
w？？？兄台你是不是发错人了？？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"icebincb"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 中午1:31
收件人:&nbsp;"XINCGer/Unity3DTraining"<Unity3DTraining@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [XINCGer/Unity3DTraining] 码云上面的也是你传的吗，两个版本的提交记录差好多哦，国内的网下github就几kb/s (#1)



我有点懵逼，我只是收藏了，这个项目啥都没动…emmmm 外加下载了一下 你是不是发错邮箱了？------------------ 原始邮件 ------------------ 
 发件人: "LiuXiong"<notifications@github.com&gt; 
 发送时间: 2019年12月17日(星期二) 中午1:28 
 收件人: "XINCGer/Unity3DTraining"<Unity3DTraining@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [XINCGer/Unity3DTraining] 码云上面的也是你传的吗，两个版本的提交记录差好多哦，国内的网下github就几kb/s (#1) 
 
 
   
 &amp;mdash;
